config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  devise_scope :user do
    match 'users/advert/:id' => 'registrations#advert', via: ['get', 'post', 'patch', 'delete']
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }

  root 'site#index', via: ['get', 'post']
  match 'news/(:alias)' => 'site#news', via: ['get', 'post']
  match 'map' => 'site#map', via: ['get', 'post']
  match 'car' => 'car#index', via: ['get', 'post']
  match 'car/advert/:id' => 'car#advert', via: ['get', 'post', 'patch']
  match 'car/:action' => 'car#:action', via: ['get', 'post', 'patch']
  match 'spare_parts' => 'hardware#spare_parts', via: ['get', 'post'] 
  match 'spare_parts/:id' => 'hardware#spare_parts_details', via: ['get', 'post'] 
  match 'techcenters' => 'techcenter#techcenters', via: ['get', 'post'] 
  match 'techcenter/:id' => 'techcenter#techcenter_details', via: ['get', 'post'] 
  match 'autoshows' => 'autoshow#autoshows', via: ['get', 'post'] 
  match 'autoshow/:id' => 'autoshow#autoshow_details', via: ['get', 'post'] 
  match ':slug' => 'site#textpage', via: ['get', 'post']

  post 'ajax/:action' => 'ajax#get_models'

end

app/views/layouts/_hardware_popup.html.erb
<div id="hardware_popup" class="form-popup">
	<a href="#" class="close-form">Закрыть</a>
	<span class="popup_header" id="popup_header">НАЙТИ ЗАПЧАСТЬ</span>
	<span class="popup_content" id="popup_content">
		<% if @shop_query.errors.count != 0 %>
			<ul class="popup_errors">
			<% @shop_query.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
			<% end %>
			</ul>
		<% end %>	
		<%= form_for @shop_query, url: '/', method: 'post' do |f|%>
			<fieldset>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</fieldset>
			<fieldset>
				<%= f.label :email %>
				<%= f.email_field :email %>
			</fieldset>
			<fieldset>
				<%= f.label :phone %>
				<%= f.text_field :phone %>
			</fieldset>
			<fieldset>
				<%= f.label :win %>
				<%= f.text_field :win %>
                <%= image_tag 'vin.jpg', :style => "margin-top: 10px;margin-right: 29px;float: right;" %>
			</fieldset>
			<fieldset>
				<%= f.label :power %>
				<%= f.number_field :power %>
			</fieldset>
			<fieldset>
				<%= f.label :size %>
				<%= f.number_field :size %>
			</fieldset>
			<fieldset>
				<%= f.label :description %>
				<%= f.text_area :description, :style => "width: 275px; height: 100px;" %>
			</fieldset>
			<%= f.hidden_field :car_mark_id %>
			<%= f.hidden_field :car_model_id %>
			<%= f.hidden_field :year %>
		<% end %>
	</span>
	<span class="popup_btn">ОТПРАВИТЬ ЗАПРОС В МАГАЗИНЫ</span>
</div>

<% if params[:shop_query] && @shop_query.errors.count != 0 %>
	<script type="text/javascript">
		$(window).load(function(){
			showForm('hardware_popup');
		});
	</script>
<% end %>
<% if params[:shop_query] && @shop_query.errors.count == 0 %>
	<script type="text/javascript">
		$(document).ready(function(){
			showSuccessForm(518, 180, 'Ваш запрос отправлен. С вами свяжутся администраторы магазинов.', 'ЗАПРОС УСПЕШНО ОТПРАВЛЕН')
		});
	</script>
<% end %>

app/views/layouts/_request_rent.html.erb
<div id="rent_popup" class="form-popup">
	<a href="#" class="close-form">Закрыть</a>
	<span class="popup_header" id="popup_header">АРЕНДОВАТЬ ПАВИЛЬОН</span>
	<span class="popup_content" id="popup_content">
		<% if @request_rent.errors.count != 0 %>
			<ul class="popup_errors">
			<% @request_rent.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
			<% end %>
			</ul>
		<% end %>	
		<%= form_for @request_rent, url: '', method: 'post' do |f|%>
			<fieldset>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</fieldset>
			<fieldset>
				<%= f.label :email %>
				<%= f.email_field :email %>
			</fieldset>
			<fieldset>
				<%= f.label :phone %>
				<%= f.text_field :phone %>
			</fieldset>

			<fieldset>
				<%= f.label :sq %>
				<%= f.number_field :sq %>
			</fieldset>
			<fieldset>
				<%= f.label :info %>
				<%= f.text_area :info, :style => "width: 275px; height: 100px;" %>
			</fieldset>
		<% end %>
	</span>
	<span class="popup_btn">ОТПРАВИТЬ ЗАПРОС</span>
</div>

<% if params[:request_rent] && @request_rent.errors.count != 0 %>
	<script type="text/javascript">
		$(document).ready(function(){
			showForm('rent_popup');
		});
	</script>
<% end %>
<% if params[:request_rent] && @request_rent.errors.count == 0 %>
	<script type="text/javascript">
		$(document).ready(function(){
			showSuccessForm(518, 180, 'Ваш запрос отправлен. С вами свяжутся администраторы.', 'ЗАПРОС УСПЕШНО ОТПРАВЛЕН')
		});
	</script>
<% end %>

app/views/layouts/_success_popup.html.erb
<div id="overlay"></div>
<div id="success_popup">
	<span class="popup_header" id="popup_header">ПОДАЧА ОБЪЯВЛЕНИЯ</span>
	<span class="popup_content" id="popup_content">Ваше объявление успешно добавлено.</span>
	<span class="popup_btn">ОК</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="keywords" content="<%= @keywords %>" />
  <meta name="description" content="<%= @description %>" />
  <meta name='yandex-verification' content='4cfc91c736158091' />
  <meta name="google-site-verification" content="ygcztvKdNi4z9VAt8XZAkN7yuw9P6wdIK6OpmBalO7U" />
  <script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
  <% if request.user_agent[/Android/] %>
  <style type="text/css">
  	.ext-search {
	    margin-top: -12px;
	}
  </style>
  <% end %>
  <% if request.user_agent[/Mozilla/] && !request.user_agent[/Android/] %>
  <style type="text/css">
  	.ext-search {
	    margin-top: 12px;
	}
  </style>
  <% end %>
   <% if request.user_agent[/Chrome/] && !request.user_agent[/Android/] %>
  <style type="text/css">
  	.ext-search {
	    margin-top: 2px;
	}
  </style>
  <% end %>
</head>
<body>
<div class="page">
	<div class="header">
		<div class="center-block">
			<a href="/"><img src="<%= image_path('logo.png') %>" class="logo" /></a>
			<ul class="menu">
				<% @menu_items.each do |i| %>
                  <li><a href="<%= i.url %>"><%= i.name %></a></li>
                <% end %>
				<li><a href="/car/send_ad">ПОДАТЬ ОБЪЯВЛЕНИЕ</a></li>
			</ul>
			<div class="clear"></div>
			<a href="#"><img src="<%= image_path('rent-btn.png') %>" class="rent-btn" /></a>
			<div class="clear"></div>
			<form class="search" action="/car">
				<input type="text" placeholder="ПОИСК СРЕДИ <%= Car.all.size %> ПРЕДЛОЖЕНИЙ" value="<%= params[:q] if !params[:q].blank? %>" name="q"/>
				<input type="submit" value="" />
			</form>
			<% if user_signed_in? %>
					<span class="welcome-text">
						<a href="/users/edit" class="cabinet-link"><%= current_user.email %></a>
						<span class="devider"><img src="<%= image_path('devider.png') %>" /></span>
						<a href="/users/edit" class="cabinet-link">Личный кабинет</a>
						<span class="devider"><img src="<%= image_path('devider.png') %>" /></span>
						<a href="/users/sign_out" class="logout_btn_header">Выход</a>
					</span>
			<% else %>
				<%= form_for(:user, :url => session_path(:user), :html => {:class => 'login'}) do |f| %>
					<a href="/users/sign_up" class="register-btn">РЕГИСТРАЦИЯ</a>
					<span class="devider"><img src="<%= image_path('devider.png') %>" /></span>
					<%= f.text_field :email, :placeholder => 'EMAIL' %>
					<%= f.password_field :password, :placeholder => 'ПАРОЛЬ' %>
					<%= f.submit '' %>
				<% end %>
			<% end %>
		</div>
	</div>
<%= yield %>

<div class="center-block" style="background: white; padding: 8px; text-align: center;width: 950px;margin-top: 12px;">
        <%= Banners.get_banner('footer_banner', nil).html_safe %>
	</div>
	<div class="center-block" style="background: white; margin-top: 12px; padding-bottom: 40px;">
		<span class="color-label"></span>
		<span class="block-header">НОВОСТИ</span>
		<ul class="news">
			<% @news_widget.each do |n| %>
				<li>
					<span class="date"><%= n.created_at.strftime('%d.%m.%Y') %></span>
					<a href="/news/<%= n.alias %>"><img src="<%= n.image.url(:thumb) %>" /></a>
					<a href="/news/<%= n.alias %>" class="news-header"><%= n.title %></a>
					<span class="news-intro"><%= n.intro.html_safe %></span>
				</li>
			<% end %>
		</ul>
		<div class="clear"></div>
	<a href="/news" class="news-archive-link">АРХИВ НОВОСТЕЙ</a>
	</div>
	<div class="center-block footer-contacts" style="background: #f5f5f5;height: 40px;">
		<%= Settings.get_param_value('city') %>, <%= Settings.get_param_value('street') %>, <%= Settings.get_param_value('phone_number_1') %>
	</div>
	<div class="center-block" style="background: white">
		<div class="map" id="map"></div>
		<span class="show-map-btn">
			<img src="<%= image_path('show-map-btn.png') %>" id="show-map-btn" />
		</span>
		<span class="print-scheme-center"><a href="#">Развернуть карту</a></span>
	</div>
	<div class="page-buffer"></div>
</div>
<div class="footer">
	<div class="center-block" style="background-color: #efefef;height: 100%">
		<ul class="footer-menu">
            <% @menu_items.each do |i| %>
              <li><a href="<%= i.url %>"><%= i.name %></a>
                <% submenus = Menu.where(:parent => i.id) %>
                <% if submenus.size != 0 %>
                	<ul class="footer-submenu">
                		<% submenus.each do |s| %>
                			<li><a href='<%= s.url %>'><%= s.name %></li>
                		<% end %>
                	</ul>
                <% end %>
                <% if i.url == '/contacts' %>
                    <div class="footer-contacts-block">
                      <%= Settings.get_param_value('footer_address') %><br />
                      <%= Settings.get_param_value('phone_number_1') %><br />
                      <%= Settings.get_param_value('phone_number_2') %><br />
                      <%= Settings.get_param_value('timework') %>
                    </div>
                <% end %>
              </li>
            <% end %>
		</ul>
		<div class="clear"></div>
		<span class="copy">Создание сайта: ACOND DESIGN</span>
		<div class="clear"></div>
	</div>
</div>
<%= render :partial => 'layouts/success_popup' %>
<%= render :partial => 'layouts/request_rent' %>
<!— Yandex.Metrika counter —>
<script type="text/javascript">
(function (d, w, c) {
(w[c] = w[c] || []).push(function() {
try {
w.yaCounter29245155 = new Ya.Metrika({id:29245155,
webvisor:true,
clickmap:true,
trackLinks:true,
accurateTrackBounce:true});
} catch(e) { }
});

var n = d.getElementsByTagName("script")[0],
s = d.createElement("script"),
f = function () { n.parentNode.insertBefore(s, n); };
s.type = "text/javascript";
s.async = true;
s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

if (w.opera == "[object Opera]") {
d.addEventListener("DOMContentLoaded", f, false);
} else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/29245155" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!— /Yandex.Metrika counter —>
</body>
</html>